from PyQt5 import QtCore, QtGui, QtWidgets


class q2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1007, 650)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(180, 150, 691, 41))
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(190, 260, 231, 19))
        self.radioButton.setObjectName("radioButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(450, 70, 151, 51))
        self.label.setObjectName("label")
        self.radioButton_4 = QtWidgets.QRadioButton(Form)
        self.radioButton_4.setGeometry(QtCore.QRect(190, 350, 115, 19))
        self.radioButton_4.setObjectName("radioButton_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(190, 210, 41, 31))
        self.label_3.setObjectName("label_3")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(190, 290, 115, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Form)
        self.radioButton_3.setGeometry(QtCore.QRect(190, 320, 115, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(240, 210, 441, 21))
        self.label_4.setObjectName("label_4")
        self.xiayiti2 = QtWidgets.QPushButton(Form)
        self.xiayiti2.setGeometry(QtCore.QRect(520, 410, 201, 51))
        self.xiayiti2.setObjectName("xiayiti2")
        self.shangyiti = QtWidgets.QPushButton(Form)
        self.shangyiti.setGeometry(QtCore.QRect(250, 410, 171, 51))
        self.shangyiti.setObjectName("shangyiti")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(140, 480, 651, 81))
        self.label_5.setObjectName("label_5")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "医药知识问答"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">亲爱的用户：感谢您使用医药知识百度问答，请回答下面的问题：</span></p></body></html>"))
        self.radioButton.setText(_translate("Form", "A.阿司匹林"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">回答问题</span></p></body></html>"))
        self.radioButton_4.setText(_translate("Form", "D.甲烷"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Q2：</span></p></body></html>"))
        self.radioButton_2.setText(_translate("Form", "B.板蓝根"))
        self.radioButton_3.setText(_translate("Form", "C.福尔马林"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">下面哪一个是中药？（单选题）</span></p></body></html>"))
        self.xiayiti2.setText(_translate("Form", "下一题"))
        self.shangyiti.setText(_translate("Form", "上一题"))
