
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(300, 50, 391, 431))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.pushButton_A = QtWidgets.QPushButton(Dialog)
        self.pushButton_A.setGeometry(QtCore.QRect(40, 50, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_A.setFont(font)
        self.pushButton_A.setObjectName("pushButton_A")
        self.pushButton_B = QtWidgets.QPushButton(Dialog)
        self.pushButton_B.setGeometry(QtCore.QRect(100, 50, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_B.setFont(font)
        self.pushButton_B.setObjectName("pushButton_B")
        self.pushButton_C = QtWidgets.QPushButton(Dialog)
        self.pushButton_C.setGeometry(QtCore.QRect(160, 50, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_C.setFont(font)
        self.pushButton_C.setObjectName("pushButton_C")
        self.pushButton_F = QtWidgets.QPushButton(Dialog)
        self.pushButton_F.setGeometry(QtCore.QRect(160, 100, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_F.setFont(font)
        self.pushButton_F.setObjectName("pushButton_F")
        self.pushButton_D = QtWidgets.QPushButton(Dialog)
        self.pushButton_D.setGeometry(QtCore.QRect(40, 100, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_D.setFont(font)
        self.pushButton_D.setObjectName("pushButton_D")
        self.pushButton_E = QtWidgets.QPushButton(Dialog)
        self.pushButton_E.setGeometry(QtCore.QRect(100, 100, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_E.setFont(font)
        self.pushButton_E.setObjectName("pushButton_E")
        self.pushButton_I = QtWidgets.QPushButton(Dialog)
        self.pushButton_I.setGeometry(QtCore.QRect(160, 150, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_I.setFont(font)
        self.pushButton_I.setObjectName("pushButton_I")
        self.pushButton_G = QtWidgets.QPushButton(Dialog)
        self.pushButton_G.setGeometry(QtCore.QRect(40, 150, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_G.setFont(font)
        self.pushButton_G.setObjectName("pushButton_G")
        self.pushButton_L = QtWidgets.QPushButton(Dialog)
        self.pushButton_L.setGeometry(QtCore.QRect(160, 200, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_L.setFont(font)
        self.pushButton_L.setObjectName("pushButton_L")
        self.pushButton_H = QtWidgets.QPushButton(Dialog)
        self.pushButton_H.setGeometry(QtCore.QRect(100, 150, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_H.setFont(font)
        self.pushButton_H.setObjectName("pushButton_H")
        self.pushButton_J = QtWidgets.QPushButton(Dialog)
        self.pushButton_J.setGeometry(QtCore.QRect(40, 200, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_J.setFont(font)
        self.pushButton_J.setObjectName("pushButton_J")
        self.pushButton_K = QtWidgets.QPushButton(Dialog)
        self.pushButton_K.setGeometry(QtCore.QRect(100, 200, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_K.setFont(font)
        self.pushButton_K.setObjectName("pushButton_K")
        self.pushButton_V = QtWidgets.QPushButton(Dialog)
        self.pushButton_V.setGeometry(QtCore.QRect(40, 400, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_V.setFont(font)
        self.pushButton_V.setObjectName("pushButton_V")
        self.pushButton_O = QtWidgets.QPushButton(Dialog)
        self.pushButton_O.setGeometry(QtCore.QRect(160, 250, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_O.setFont(font)
        self.pushButton_O.setObjectName("pushButton_O")
        self.pushButton_W = QtWidgets.QPushButton(Dialog)
        self.pushButton_W.setGeometry(QtCore.QRect(100, 400, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_W.setFont(font)
        self.pushButton_W.setObjectName("pushButton_W")
        self.pushButton_S = QtWidgets.QPushButton(Dialog)
        self.pushButton_S.setGeometry(QtCore.QRect(40, 350, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_S.setFont(font)
        self.pushButton_S.setObjectName("pushButton_S")
        self.pushButton_X = QtWidgets.QPushButton(Dialog)
        self.pushButton_X.setGeometry(QtCore.QRect(160, 400, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_X.setFont(font)
        self.pushButton_X.setObjectName("pushButton_X")
        self.pushButton_M = QtWidgets.QPushButton(Dialog)
        self.pushButton_M.setGeometry(QtCore.QRect(40, 250, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_M.setFont(font)
        self.pushButton_M.setObjectName("pushButton_M")
        self.pushButton_T = QtWidgets.QPushButton(Dialog)
        self.pushButton_T.setGeometry(QtCore.QRect(100, 350, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_T.setFont(font)
        self.pushButton_T.setObjectName("pushButton_T")
        self.pushButton_R = QtWidgets.QPushButton(Dialog)
        self.pushButton_R.setGeometry(QtCore.QRect(160, 300, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_R.setFont(font)
        self.pushButton_R.setObjectName("pushButton_R")
        self.pushButton_U = QtWidgets.QPushButton(Dialog)
        self.pushButton_U.setGeometry(QtCore.QRect(160, 350, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_U.setFont(font)
        self.pushButton_U.setObjectName("pushButton_U")
        self.pushButton_N = QtWidgets.QPushButton(Dialog)
        self.pushButton_N.setGeometry(QtCore.QRect(100, 250, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_N.setFont(font)
        self.pushButton_N.setObjectName("pushButton_N")
        self.pushButton_P = QtWidgets.QPushButton(Dialog)
        self.pushButton_P.setGeometry(QtCore.QRect(40, 300, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_P.setFont(font)
        self.pushButton_P.setObjectName("pushButton_P")
        self.pushButton_Q = QtWidgets.QPushButton(Dialog)
        self.pushButton_Q.setGeometry(QtCore.QRect(100, 300, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_Q.setFont(font)
        self.pushButton_Q.setObjectName("pushButton_Q")
        self.pushButton_Y = QtWidgets.QPushButton(Dialog)
        self.pushButton_Y.setGeometry(QtCore.QRect(40, 450, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_Y.setFont(font)
        self.pushButton_Y.setObjectName("pushButton_Y")
        self.pushButton_Z = QtWidgets.QPushButton(Dialog)
        self.pushButton_Z.setGeometry(QtCore.QRect(100, 450, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_Z.setFont(font)
        self.pushButton_Z.setObjectName("pushButton_Z")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(645, 545, 100, 30))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "按字母查询科室"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "序号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "科室"))
        self.pushButton_A.setText(_translate("Dialog", "A"))
        self.pushButton_B.setText(_translate("Dialog", "B"))
        self.pushButton_C.setText(_translate("Dialog", "C"))
        self.pushButton_F.setText(_translate("Dialog", "F"))
        self.pushButton_D.setText(_translate("Dialog", "D"))
        self.pushButton_E.setText(_translate("Dialog", "E"))
        self.pushButton_I.setText(_translate("Dialog", "I"))
        self.pushButton_G.setText(_translate("Dialog", "G"))
        self.pushButton_L.setText(_translate("Dialog", "L"))
        self.pushButton_H.setText(_translate("Dialog", "H"))
        self.pushButton_J.setText(_translate("Dialog", "J"))
        self.pushButton_K.setText(_translate("Dialog", "K"))
        self.pushButton_V.setText(_translate("Dialog", "V"))
        self.pushButton_O.setText(_translate("Dialog", "O"))
        self.pushButton_W.setText(_translate("Dialog", "W"))
        self.pushButton_S.setText(_translate("Dialog", "S"))
        self.pushButton_X.setText(_translate("Dialog", "X"))
        self.pushButton_M.setText(_translate("Dialog", "M"))
        self.pushButton_T.setText(_translate("Dialog", "T"))
        self.pushButton_R.setText(_translate("Dialog", "R"))
        self.pushButton_U.setText(_translate("Dialog", "U"))
        self.pushButton_N.setText(_translate("Dialog", "N"))
        self.pushButton_P.setText(_translate("Dialog", "P"))
        self.pushButton_Q.setText(_translate("Dialog", "Q"))
        self.pushButton_Y.setText(_translate("Dialog", "Y"))
        self.pushButton_Z.setText(_translate("Dialog", "Z"))
        self.pushButton_3.setText(_translate("Dialog", "返回"))
